# ============================================================
# services/duplicate_checker.py
# Detects duplicate / near-duplicate questions using word overlap
# and simple similarity scoring
# ============================================================
import re
from typing import List, Tuple

STOP_WORDS = {
    "the","a","an","is","are","was","were","be","been","being",
    "have","has","had","do","does","did","will","would","could",
    "should","may","might","shall","can","need","dare","ought",
    "used","to","of","in","on","at","by","for","with","about",
    "against","between","into","through","during","before","after",
    "above","below","from","up","down","out","off","over","under",
    "again","further","then","once","what","which","who","whom",
    "this","that","these","those","and","but","or","nor","not",
    "so","yet","both","either","neither","how","when","where","why",
}


def _tokenize(text: str) -> set:
    words = re.findall(r'\b[a-z]{3,}\b', text.lower())
    return {w for w in words if w not in STOP_WORDS}


def similarity_score(text1: str, text2: str) -> float:
    """Jaccard similarity between two question texts. 0.0–1.0"""
    s1 = _tokenize(text1)
    s2 = _tokenize(text2)
    if not s1 or not s2:
        return 0.0
    intersection = len(s1 & s2)
    union = len(s1 | s2)
    return intersection / union if union else 0.0


def is_duplicate(new_text: str, existing_texts: List[str],
                 threshold: float = 0.55) -> Tuple[bool, int]:
    """
    Returns (is_dup, index_of_duplicate) or (False, -1).
    threshold 0.55 = 55% word overlap → duplicate
    """
    for idx, existing in enumerate(existing_texts):
        score = similarity_score(new_text, existing)
        if score >= threshold:
            return True, idx
    return False, -1


def deduplicate_generated(questions: List[str],
                           threshold: float = 0.50) -> List[str]:
    """
    Remove near-duplicate questions from a list generated by AI.
    """
    unique = []
    for q in questions:
        dup, _ = is_duplicate(q, unique, threshold)
        if not dup:
            unique.append(q)
    return unique


def check_syllabus_relevance(question_text: str,
                              topic_keywords: List[str],
                              min_matches: int = 1) -> bool:
    """
    Check if a generated question is relevant to the syllabus topics.
    Returns True if at least min_matches keywords found in question.
    """
    q_lower = question_text.lower()
    matches = sum(1 for kw in topic_keywords
                  if kw.lower() in q_lower and len(kw) > 3)
    return matches >= min_matches
