# ============================================================
# services/pdf_service.py — ReportLab PDF generator
# ============================================================
import tempfile, os
from datetime import datetime


def generate_pdf(paper_data: dict) -> str:
    try:
        return _reportlab_pdf(paper_data)
    except ImportError:
        return _text_fallback(paper_data)
    except Exception as e:
        print(f"[PDF] Error: {e}")
        return _text_fallback(paper_data)


def _reportlab_pdf(paper_data: dict) -> str:
    from reportlab.lib.pagesizes   import A4
    from reportlab.lib.styles      import ParagraphStyle
    from reportlab.lib.units       import cm
    from reportlab.lib             import colors
    from reportlab.platypus        import (SimpleDocTemplate, Paragraph,
                                            Spacer, HRFlowable)
    from reportlab.lib.enums       import TA_CENTER, TA_JUSTIFY

    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf", prefix="examai_")
    tmp.close()

    INK   = colors.HexColor("#1a1a2e")
    GOLD  = colors.HexColor("#c9973a")
    GREY  = colors.HexColor("#666666")
    W, H  = A4

    doc = SimpleDocTemplate(tmp.name, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm, topMargin=1.8*cm, bottomMargin=1.8*cm)

    s_college = ParagraphStyle("c", fontSize=13, fontName="Helvetica-Bold",
                                alignment=TA_CENTER, spaceAfter=2)
    s_dept    = ParagraphStyle("d", fontSize=10, fontName="Helvetica",
                                alignment=TA_CENTER, spaceAfter=4)
    s_exam    = ParagraphStyle("e", fontSize=11, fontName="Helvetica-Bold",
                                alignment=TA_CENTER, spaceAfter=6)
    s_sec     = ParagraphStyle("s", fontSize=9,  fontName="Helvetica-Bold",
                                backColor=INK, textColor=colors.white,
                                leftIndent=4, spaceBefore=8, spaceAfter=6, leading=16)
    s_body    = ParagraphStyle("b", fontSize=10, fontName="Helvetica",
                                spaceAfter=3, spaceBefore=4, alignment=TA_JUSTIFY)
    s_opt     = ParagraphStyle("o", fontSize=9.5, fontName="Helvetica",
                                leftIndent=20, spaceAfter=1)
    s_ans     = ParagraphStyle("a", fontSize=8.5, fontName="Helvetica-Oblique",
                                textColor=GREY, leftIndent=20, spaceAfter=4)
    s_footer  = ParagraphStyle("f", fontSize=7.5, fontName="Helvetica",
                                textColor=GREY, alignment=TA_CENTER)

    story = []
    college = paper_data.get("college_name", "VisionCampus University")
    dept    = paper_data.get("department",   "Computer Science")
    subject = paper_data.get("subject",      "Subject")
    exam_t  = paper_data.get("exam_type",    "Examination")
    marks   = paper_data.get("total_marks",  100)
    dur     = paper_data.get("duration",     "3 Hours")

    story.append(Paragraph(college.upper(), s_college))
    story.append(Paragraph(f"Department of {dept}", s_dept))
    story.append(HRFlowable(width="100%", thickness=2, color=INK, spaceAfter=4))
    story.append(Paragraph(f"{exam_t} — April 2025", s_exam))
    story.append(Paragraph(
        f"Subject: <b>{subject}</b>&nbsp;|&nbsp;Duration: <b>{dur}</b>&nbsp;|&nbsp;Max Marks: <b>{marks}</b>",
        s_dept))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey, spaceBefore=4, spaceAfter=8))

    content = paper_data.get("content", "")
    for line in content.splitlines():
        line = line.strip()
        if not line:
            story.append(Spacer(1, 4))
            continue
        if line.startswith("SECTION") and ("—" in line or "[" in line):
            story.append(Paragraph(f"&nbsp; {line} &nbsp;", s_sec))
        elif line.startswith("━"):
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey,
                                     spaceBefore=3, spaceAfter=3))
        elif line.startswith("✓ Correct") or line.startswith("[Topic:"):
            story.append(Paragraph(line, s_ans))
        elif len(line) > 2 and line[0].isalpha() and line[1] == ")":
            story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;{line}", s_opt))
        elif line.startswith("Q") and "." in line[:5]:
            story.append(Paragraph(f"<b>{line}</b>", s_body))
        elif "END OF QUESTION PAPER" in line or "Generated by ExamAI" in line:
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey,
                                     spaceBefore=8, spaceAfter=4))
            story.append(Paragraph(line, s_footer))
        elif line.startswith("(a)") or line.startswith("(b)"):
            story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;{line}", s_body))
        else:
            story.append(Paragraph(line, s_body))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph(
        f"ExamAI Syllabus-Based Generator &nbsp;|&nbsp; {datetime.now().strftime('%d %b %Y %H:%M')}",
        s_footer))

    doc.build(story)
    return tmp.name


def _text_fallback(paper_data: dict) -> str:
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".txt", prefix="examai_",
                                      mode="w", encoding="utf-8")
    tmp.write(paper_data.get("content", "No content."))
    tmp.close()
    return tmp.name
